version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
    exclude-paths:
      - "locks/requirements-dev-py314.txt"
      - "locks/requirements-runtime-py314.txt"
    groups:
      development-patch-minor:
        applies-to: version-updates
        dependency-type: development
        update-types:
          - "patch"
          - "minor"
      runtime-production:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - "patch"
          - "minor"
          - "major"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - deps:github-actions
    groups:
      github-actions:
        patterns:
          - "*"
